---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
      provision_command: 
        - apt-get install net-tools

